### ISSUE TITLE
Installing new demon, throws error.

### ISSUE THREAD

**Issue by ghost** [SpaceCP/Bugs#110]
root@ns509115:~# node houston start

module.js:340
    throw err;
          ^
Error: Cannot find module '/root/houston'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by JamyDev** [comment]
This is not a bug, please cd into the directory where you unzipped houston.
