### ISSUE TITLE
Error in console when executing scheduler task that requires parameter in task

### ISSUE THREAD

**Issue by tips48** [SpaceCP/Bugs#118]
Open Build 7.

Steps to reproduce:
1) Create this schedule: http://puu.sh/mk2QG/61ce997c63.png
2) Manually execute the schedule with the Run Schedule button

Error in console:

```
spigot-mc: [22:45:13 WARN]: [Houston] An unknown exception occurred
- spigot-mc: java.lang.IllegalStateException: Method banPlayer expects [class java.lang.String, class java.lang.String, class java.lang.Number, class java.lang.String], an incorrect amount was given.
- spigot-mc:    at net.xereo.houston.java.methods.MethodPacketHandler.handle(MethodPacketHandler.java:95) ~[houstonbukkit.jar:?]
- spigot-mc:    at net.xereo.houston.java.connection.ConnectionManager.received(ConnectionManager.java:157) [houstonbukkit.jar:?]
- spigot-mc:    at net.xereo.houston.java.connection.HoustonWSClient.onMessage(HoustonWSClient.java:50) [houstonbukkit.jar:?]
- spigot-mc:    at net.xereo.houston.websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:312) [houstonbukkit.jar:?]
- spigot-mc:    at net.xereo.houston.websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368) [houstonbukkit.jar:?]
- spigot-mc:    at net.xereo.houston.websocket.WebSocketImpl.decode(WebSocketImpl.java:157) [houstonbukkit.jar:?]
- spigot-mc:    at net.xereo.houston.websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230) [houstonbukkit.jar:?]
- spigot-mc:    at net.xereo.houston.websocket.client.WebSocketClient.run(WebSocketClient.java:188) [houstonbukkit.jar:?]
- spigot-mc:    at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
```

I assume this is the same for most of the tasks that require a parameter.

**Comment by tlaundal** [comment]
I think this is a panel problem, but I have to investigate what the panel is sending to Houston.

**Comment by tlaundal** [comment]
This is a panel problem, the panel thinks the ban player method only takes the player and reason as arguments, but in reality it takes an expiration date and a source, too.

This probably happened because the method is different from our Vanilla API implementation to Bukkit API. We are working on an unified API, and this probably won't be fixed till then.

**Comment by philip-ulrich** [comment]
I think it is known, but this issue includes the broadcast function as well:
`[14:16:38 WARN]: [Houston] An unknown exception occurred
java.lang.IllegalStateException: Method broadcast expects [class java.lang.String, class java.lang.String], an incorrect amount was given.
at net.xereo.houston.java.methods.MethodPacketHandler.handle(MethodPacketHandler.java:95) ~[houstonbukkit.jar:?]
at net.xereo.houston.java.connection.ConnectionManager.received(ConnectionManager.java:172) [houstonbukkit.jar:?]
at net.xereo.houston.java.connection.HoustonWSClient.onMessage(HoustonWSClient.java:41) [houstonbukkit.jar:?]
at net.xereo.houston.websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:312) [houstonbukkit.jar:?]
at net.xereo.houston.websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368) [houstonbukkit.jar:?]
at net.xereo.houston.websocket.WebSocketImpl.decode(WebSocketImpl.java:157) [houstonbukkit.jar:?]
at net.xereo.houston.websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230) [houstonbukkit.jar:?]
at net.xereo.houston.websocket.client.WebSocketClient.run(WebSocketClient.java:188) [houstonbukkit.jar:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]`
