### ISSUE TITLE
Invalid game provided ( on demon side )

### ISSUE THREAD

**Issue by Rustypredator** [SpaceCP/Bugs#128]
I set up the deamon successfully, and it is connecting properly.
However, when i hit "create your minecraft Server now" on the creation dialog it crashes the deamon instantly with the following error:

```
florian@SpaceCPTest ~/spacecp $ node houston start
info: [bootstrap] Checking module existence...
info: [bootstrap] Module check completed.
info: Starting Houston (Build: 198)
info: info: [wrapper] Checking for updates...
info: info: [wrapper] Houston is up to date!
info: Checking Houston integrity...
info: Integrity check complete!
info: Starting internal WebSocket server listening on 35565...
info: Starting remote WebSocket server listening on 35566...
info: Calling back to SpaceCP...
info: WebSocket manager running!
info: [upload] Uploads manager activated.
info: Houston start completed.
info: [network] Successfully called back to SpaceCP
info: [network] Connection from SpaceCP/cli accepted.
The following errors occured: Invalid game provided. OperationalError: The following errors occured: Invalid game provided.
    at k.create (/home/florian/spacecp/houston.js:9:10271)
    at o.createServer (/home/florian/spacecp/houston.js:5:6718)
    at F.f.createServer (/home/florian/spacecp/houston.js:5:28041)
    at F.delegateMethodCall (/home/florian/spacecp/houston.js:4:24888)
    at WebSocket.<anonymous> (/home/florian/spacecp/houston.js:4:24382)
    at emitThree (events.js:97:13)
    at WebSocket.emit (events.js:175:7)
    at WebSocket.<anonymous> (/home/florian/spacecp/houston.js:7:10650)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.self._receiver.ontext (/home/florian/spacecp/node_modules/ws/lib/WebSocket.js:682:10)
    at Receiver.opcodes.1.finish (/home/florian/spacecp/node_modules/ws/lib/Receiver.js:391:14)
    at Receiver.expectHandler (/home/florian/spacecp/node_modules/ws/lib/Receiver.js:372:33)
    at Receiver.add (/home/florian/spacecp/node_modules/ws/lib/Receiver.js:87:24)
    at TLSSocket.firstHandler (/home/florian/spacecp/node_modules/ws/lib/WebSocket.js:663:22)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)
info: Houston will now shut down...
8 Jan 20:30:04 - uncaughtException: a0ec566085624376b487a50a129e162e
info: Houston exiting.
```

Version info of node:

```
florian@SpaceCPTest ~/spacecp $ node -v
v5.4.0
```

The Testserver is a clean setup on debian 8.2

**Comment by tlaundal** [comment]
Hmm. Could you list the contents of the `addons` folder for us?

**Comment by Rustypredator** [comment]
There is nothing in there

**Comment by tlaundal** [comment]
Well, that would be the reason. 

The solution is to redownload Houston and extract it in the same folder again. I don't think you will have to reinstall. 

Do you have any idea why the files in `addons` wasn't extracted? Could you post all the comands, or steps you took to install Houston?

**Comment by Rustypredator** [comment]
okay, now the folder contains two other folders named "houston_game_minecraft" and "houston_mod_bukkit".
It does not throw errors anymore.
But now it does'nt do anything more. the setup on the webinterface is just saying "wait while we setup your server"
and nothing happens on the deamon.

**Comment by tlaundal** [comment]
Ok, then we are one step on the way. 

Are you now talking about the same server you started setting up when the error happend? Try creating a new one.

**Comment by Rustypredator** [comment]
i should reinstall the server? or what do you mean?
I did not set up a server through spacecp yet.. only the deamon

**Comment by jithatsonei** [comment]
To confirm, the daemon is added and setup, but when attempting to setup your first server it hangs with the message 'wait while we setup your server'

**Comment by tlaundal** [comment]
I see I misunderstood you @Rustypredator.
As the original issue is now resolved. Please create a new issue for the new problem.
