### ISSUE TITLE
Minecraft 1.9 Support

### ISSUE THREAD

**Issue by NicoDreamzZ** [SpaceCP/Bugs#180]
With Spigot 1.9 following error occurs:

`[13:55:39 WARN]: [Houston] Task #2 for Houston v1.0-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
at net.xereo.houston.bukkit.events.PlayerEvents.poll(PlayerEvents.java:98) ~[?:?]
at net.xereo.houston.java.events.PropertyEventManager.run(PropertyEventManager.java:65) ~[?:?]
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]`

Please fix this, so that i can test my plugins whithout any errors spaming the console.

**Comment by jithatsonei** [comment]
What OS is houston on?

**Comment by NicoDreamzZ** [comment]
Debian 7 and Debian 8 tested, error occurs on both systems.

**Comment by JamyDev** [comment]
Try the dev version https://dl.spacecp.net/houston/houston_252_1457019389.zip
