### ISSUE TITLE
SpaceCP Problem with Modpacks

### ISSUE THREAD

**Issue by CreeperHD** [SpaceCP/Bugs#181]
Hello , I have a problem and although I would like to make about a SpaceCP Modpack server of FTB wenich select them Coustom modpacks and dan the download link from the FTB Server insert , the the server not downloading why is that ?

**Comment by JamyDev** [comment]
Can you check the console of the daemon for any download errors?

**Comment by CreeperHD** [comment]
[TypeError: g.createReadSteam is not a function]
error: creeperlife-test: Failed to download the mod., server=creeperlife-test, b
uild=1457019389_252

this is in the console wehn i download the modpack

**Comment by JamyDev** [comment]
Can you post the link to the modpack?

**Comment by CreeperHD** [comment]
http://addons-origin.cursecdn.com/files/2272/696/FTBDirewolf20Server-1.10.0-1.7.10.zip this is the download link from the modpack FTB Present Direwolf20 (v1.10.0) Minecraft Version 1.7.10

**Comment by JamyDev** [comment]
Thanks, I'll investigate in a bit.

**Comment by CreeperHD** [comment]
Hello I wanted to ask times as it looks now with the modpacks you can install it now or still ?

**Comment by JamyDev** [comment]
Hadn't had a lot of time to look into it, I'll add it to my todo for tonight!

**Comment by JamyDev** [comment]
I'm able to download this just fine. Except for the fact that the Minecraft jar isn't included.

**Comment by Colinstech** [comment]
ftb doesnt use minecraft jar, it uses ftb_server.jar, that you run with the serverstart.bat

**Comment by Colinstech** [comment]
because it loads peices from the minecraft jar, which it downloads, and from the ftb server jar.

**Comment by JamyDev** [comment]
Use the jar selector in the server preferences ;)

**Comment by Colinstech** [comment]
i cant select .bat files though. running just ftb_server doesnt do anything, and just minecraft jar loads normal minecraft.
i can post screenshots if it would help. :-)

I think this is what the origonal author ment.

**Comment by JamyDev** [comment]
Check the console to see what it says when running the ftb_server jar

**Comment by Colinstech** [comment]
Currently moving the daemon to a different hard drive for more space. So ill be a bit. :(

**Comment by Colinstech** [comment]
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/Level
at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.Level
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 8 more

But if i run the serverstart.bat it runs just fine.

**Comment by JamyDev** [comment]
Right the forge setup thing. You'll have to run that manually..

I don't know the exact commands but you can find them here http://files.minecraftforge.net/

I'm planning on finding a solution for these unnecessarily messy installs >_>

**Comment by Colinstech** [comment]
ok. thank you. been trying to figure it out for about a week. i don't like asking for help. ^^

**Comment by xCausxn** [comment]
http://servers.technicpack.net/Technic/servers/blightfall/Blightfall_Server_v2.1.5.zip also doesnt work so logging in similar issue,

Could be an error in request, however the error in the daemon console is:

```
info: [network] Connection from SpaceCP/cli accepted.
"toString()" failed Error: "toString()" failed
    at Buffer.toString (buffer.js:528:11)
    at BufferList.toString (/root/node_modules/bl/bl.js:178:33)
    at Request.<anonymous> (/root/node_modules/request/request.js:1042:32)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/root/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by incognitojam** [comment]
I have also repeated the same error as @xCausxn using the FTB SkyFactory 2.5 modpack (found here: https://mods.curse.com/modpacks/minecraft/245163-ftb-presents-skyfactory-2-5/2320669). I downloaded the zip and uploaded it to my own file host (so that it is a .zip url, not a redirect) and it continues to not work.
