### ISSUE TITLE
Is time based trigger working?

### ISSUE THREAD

**Issue by Forge-Media** [SpaceCP/Bugs#184]
I'm trying to setup a nightly server restart. I'm using the following cron expression 
`0 0 1 1/1 * ? *`

This should result in a daily timer which goes of at 1:00am. however, SpaceCP is showing the following:

`00:00 on the 1st in Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov and Dec`

_Used the following cron maker: http://www.cronmaker.com/_

**Comment by JamyDev** [comment]
Question marks are currently not supported in our cron library afaik

**Comment by Forge-Media** [comment]
What should I use then to make a daily time based trigger?

Never-mind using the following works:
`30 2 * * *`

**Comment by Forge-Media** [comment]
Getting the following errors when trying to run the following scheduled broadcast:

_EDIT: Using the "Say Something" task seems to work, but not the broadcast._

![screenshot-app spacecp net 2016-03-25 21-59-20](https://cloud.githubusercontent.com/assets/7041755/14054886/db870eda-f2d4-11e5-81ed-0ab7b746c2f2.png)

```
[21:57:36 WARN]: [Houston] An unknown exception occurred
java.lang.IllegalStateException: Method broadcast expects [class java.lang.String, class java.lang.String], an incorrect amount was given.
at net.xereo.houston.java.methods.MethodPacketHandler.handle(MethodPacketHandler.java:95) ~[houstonbukkit.jar:?]
at net.xereo.houston.java.connection.ConnectionManager.received(ConnectionManager.java:172) [houstonbukkit.jar:?]
at net.xereo.houston.java.connection.HoustonWSClient.onMessage(HoustonWSClient.java:41) [houstonbukkit.jar:?]
at net.xereo.houston.websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:312) [houstonbukkit.jar:?]
at net.xereo.houston.websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368) [houstonbukkit.jar:?]
at net.xereo.houston.websocket.WebSocketImpl.decode(WebSocketImpl.java:157) [houstonbukkit.jar:?]
at net.xereo.houston.websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230) [houstonbukkit.jar:?]
at net.xereo.houston.websocket.client.WebSocketClient.run(WebSocketClient.java:188) [houstonbukkit.jar:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```

**Comment by tlaundal** [comment]
That error comes because of some inconsistencies between our implementation of vanilla and bukkit on the panel. 
We are looking at a fix for this.

**Comment by tlaundal** [comment]
Because the problem that was described has been fixed, I'm closing this issue.
For the other issue reported here, about the error from Houston, see #118, as this is, in the source code, the same problem.
