### ISSUE TITLE
Unexpected token ILLEGAL upon `node houston update`

### ISSUE THREAD

**Issue by philip-ulrich** [SpaceCP/Bugs#193]
After updating the daemon, I now receive the following error when trying to start it:

`info: Checking dependencies for houston_game_minecraft

/home/endermelon/addons/houston_game_minecraft/MinecraftServer.js:82
    $server.api = Houston.apiManager.addSection(`server:${$server.id}`, "minec
                                                ^
failed to require "/home/endermelon//addons/houston_game_minecraft/MinecraftServer.js" from root
Unexpected token ILLEGAL
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at c (/home/endermelon/houston.js:4:212)
    at b (/home/endermelon/houston.js:4:895)
    at /home/endermelon/houston.js:4:17010
    at /home/endermelon/houston.js:4:15536
    at Object.oncomplete (fs.js:108:15) Error: failed to require "/home/endermelon//addons/houston_game_minecraft/MinecraftServer.js" from root
Unexpected token ILLEGAL
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at c (/home/endermelon/houston.js:4:212)
    at b (/home/endermelon/houston.js:4:895)
    at /home/endermelon/houston.js:4:17010
    at /home/endermelon/houston.js:4:15536
    at Object.oncomplete (fs.js:108:15)
    at c (/home/endermelon/houston.js:4:232)
    at b (/home/endermelon/houston.js:4:895)
    at /home/endermelon/houston.js:4:17010
    at /home/endermelon/houston.js:4:15536
    at Object.oncomplete (fs.js:108:15)
info: Houston will now shut down...
8 Apr 15:37:13 - uncaughtException: 43cb9ff6822f41979a18a9730e456b51
info: Houston exiting.`

**Comment by JamyDev** [comment]
Please install nodejs v4 or higher [LINK](https://nodejs.org/en/download/package-manager/)

**Comment by philip-ulrich** [comment]
Good call. This made the daemon start again.  Cheers.
