### ISSUE TITLE
Bukkit Plugin Throwing getPlayers Errors Again

### ISSUE THREAD

**Issue by philip-ulrich** [SpaceCP/Bugs#215]
## Expected Behavior

The bukkit plugin to work without errors
## Current Behavior

[09:33:38 WARN]: [Houston] An unknown exception occurred
java.lang.IllegalStateException: Method getPlayers expects [], an incorrect amount was given.
at net.xereo.houston.java.methods.MethodPacketHandler.handle(MethodPacketHandler.java:95) ~[houstonbukkit.jar:?]
at net.xereo.houston.java.connection.ConnectionManager.received(ConnectionManager.java:172) [houstonbukkit.jar:?]
at net.xereo.houston.java.connection.HoustonWSClient.onMessage(HoustonWSClient.java:41) [houstonbukkit.jar:?]
at net.xereo.houston.websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:312) [houstonbukkit.jar:?]
at net.xereo.houston.websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368) [houstonbukkit.jar:?]
at net.xereo.houston.websocket.WebSocketImpl.decode(WebSocketImpl.java:157) [houstonbukkit.jar:?]
at net.xereo.houston.websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230) [houstonbukkit.jar:?]
at net.xereo.houston.websocket.client.WebSocketClient.run(WebSocketClient.java:188) [houstonbukkit.jar:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
## Steps to Reproduce (for bugs)
1. Install Spigot (I'm on 1.9.2)
2. Start it up
3. Navigate in the panel
4. ???
5. Profit
## Context

It's annoying and it's causing issues with the panel such as not showing online players 
## Your Environment

Spigot 1.9.2 R0.1 Snapshot
Houston Daemon 0.0.1

**Comment by Willsr71** [comment]
Duplicate of #212 ?

**Comment by philip-ulrich** [comment]
I must be blind. I swear I looked for a duplicate. Lol

**Comment by Willsr71** [comment]
Lol gg.

**Comment by philip-ulrich** [comment]
I think it's because yours was labeled specifically for 1.7/1.8. I must have just ignored it.

**Comment by Willsr71** [comment]
Yeah  I just assumed it would work for 1.9 because of #166. Time to change the title.
