### ISSUE TITLE
Error: 479a2bc950d6477fa07635c45036dcfd at deamon installation

### ISSUE THREAD

**Issue by scrapes** [SpaceCP/Bugs#234]
node houston start gives the error 479a2bc950d6477fa07635c45036dcfd 

OS is CentOS 7 /root/spacecp/

LOG:

```
[root@h2515035 spacecp]# node houston start
info: [bootstrap] Checking module existence...
info: [bootstrap] Module check completed.
info: Starting Houston (Build: 265)
info: info: [wrapper] Checking for updates...
info: info: [wrapper] Houston is up to date!
info: Checking Houston integrity...
info: Integrity check complete!
info: Checking dependencies for houston_game_minecraft

/root/spacecp/addons/houston_game_minecraft/MinecraftServer.js:82
    $server.api = Houston.apiManager.addSection(`server:${$server.id}`, "minec
                                                ^
failed to require "/root/spacecp//addons/houston_game_minecraft/MinecraftServer.js" from root
Unexpected token ILLEGAL
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at c (/root/spacecp/houston.js:4:212)
    at b (/root/spacecp/houston.js:4:895)
    at /root/spacecp/houston.js:4:17010
    at /root/spacecp/houston.js:4:15522
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12) Error: failed to require "/root/spacecp//addons/houston_game_minecraft/MinecraftServer.js" from root
Unexpected token ILLEGAL
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at c (/root/spacecp/houston.js:4:212)
    at b (/root/spacecp/houston.js:4:895)
    at /root/spacecp/houston.js:4:17010
    at /root/spacecp/houston.js:4:15522
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
    at c (/root/spacecp/houston.js:4:232)
    at b (/root/spacecp/houston.js:4:895)
    at /root/spacecp/houston.js:4:17010
    at /root/spacecp/houston.js:4:15522
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
info: Houston will now shut down...
30 Sep 17:34:24 - uncaughtException: 479a2bc950d6477fa07635c45036dcfd
info: Houston exiting.

```

**Comment by JamyDev** [comment]
Old version of NodeJS, please use Node 6 or later
