### ISSUE TITLE
Error At Daemon INstall 

### ISSUE THREAD

**Issue by dotModded** [SpaceCP/Bugs#237]
info: [bootstrap] Checking module existence...
info: [bootstrap] Module check completed.
info: Starting Houston (Build: 265)
info: info: [wrapper] Checking for updates...
(node:3213) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
info: info: [wrapper] Houston is up to date!
info: Checking Houston integrity...
info: Integrity check complete!
info: Checking dependencies for houston_game_minecraft
info: Checking dependencies for houston_lib_minecraft
info: Checking dependencies for houston_lib_ws
info: Checking dependencies for houston_mod_bukkit
info: Checking dependencies for houston_mod_bungeecord
info: Starting internal WebSocket server listening on 35565...
info: Starting remote WebSocket server listening on 35566...
info: Calling back to SpaceCP...
info: WebSocket manager running!
info: [upload] Uploads manager activated.
info: Houston start completed.
18 Oct 18:21:21 - uncaughtException: 4fedba33e0764c10b2039a16cdcd5da8
listen EADDRINUSE 127.0.0.1:35565 Error: listen EADDRINUSE 127.0.0.1:35565
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at net.js:1403:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
info: Houston will now shut down...
18 Oct 18:21:21 - uncaughtException: e76b9075694e43cdb2fbd5e82fb336a4
listen EADDRINUSE :::35566 Error: listen EADDRINUSE :::35566
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at net.js:1403:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
info: Houston will now shut down...
info: [network] Successfully called back to SpaceCP
info: Houston exiting.

**Comment by Willsr71** [comment]
`listen EADDRINUSE 127.0.0.1:35565 Error: listen EADDRINUSE 127.0.0.1:35565`
This means that you have something already using that port, and judging from the fact that both of them are in use, you might already have a daemon instance open. Try killing that or any other processes that are using those ports and try again.
