### ISSUE TITLE
Unexpected Token ILLEGEAL

### ISSUE THREAD

**Issue by mwalden2004** [SpaceCP/Bugs#240]
Unexpected token ILLEGAL
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at c (/pls/houston.js:4:212)
    at b (/pls/houston.js:4:895)
    at /pls/houston.js:4:17010
    at /pls/houston.js:4:15536
    at Object.oncomplete (fs.js:107:15) Error: failed to require "/pls//addons/houston_game_minecraft/MinecraftServer.js" from root

**Comment by Willsr71** [comment]
Could you be a bit more specific as to what you were trying to do (install, start, stop)? and what you were using for software (os, nodejs). Basically just use the ticket format please.

**Comment by mwalden2004** [comment]
Im running Ubuntu Server, This is affter instalation, Iv tried uninstalling, and reinstalling same error. 
info: Checking dependencies for houston_game_minecraft

/SpaceCP/addons/houston_game_minecraft/MinecraftServer.js:82
    $server.api = Houston.apiManager.addSection(`server:${$server.id}`, "minec
                                                ^
failed to require "/SpaceCP//addons/houston_game_minecraft/MinecraftServer.js" from root
Unexpected token ILLEGAL
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at c (/SpaceCP/houston.js:4:212)
    at b (/SpaceCP/houston.js:4:895)
    at /SpaceCP/houston.js:4:17010
    at /SpaceCP/houston.js:4:15536
    at Object.oncomplete (fs.js:107:15) Error: failed to require "/SpaceCP//addons/houston_game_minecraft/MinecraftServer.js" from root
Unexpected token ILLEGAL
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at c (/SpaceCP/houston.js:4:212)
    at b (/SpaceCP/houston.js:4:895)
    at /SpaceCP/houston.js:4:17010
    at /SpaceCP/houston.js:4:15536
    at Object.oncomplete (fs.js:107:15)
    at c (/SpaceCP/houston.js:4:232)
    at b (/SpaceCP/houston.js:4:895)
    at /SpaceCP/houston.js:4:17010
    at /SpaceCP/houston.js:4:15536
    at Object.oncomplete (fs.js:107:15)
info: Houston will now shut down...
13 Nov 08:33:43 - uncaughtException: 6bca27dc3585446d8aa9960401bfbc80
info: Houston exiting.

**Comment by TehEnderz** [comment]
What version of Node.js are you using? I had the same issue on Turnkey Linux because the version of Node.js in the included repositories was outdated. Now it works just fine for me on version 6.9.1.

**Comment by mwalden2004** [comment]
I fixed it by upgrading from Ubuntu Server 15.10 to 16.045=
