### ISSUE TITLE
I finished the install, and then i try to start the panel:

### ISSUE THREAD

**Issue by mwalden2004** [SpaceCP/Bugs#241]
I'm using UBUNTU 15.10 Server, and it is running NODEjs
/SpaceCP/addons/houston_game_minecraft/MinecraftServer.js:82
    $server.api = Houston.apiManager.addSection(`server:${$server.id}`, "minec
                                                ^
failed to require "/SpaceCP//addons/houston_game_minecraft/MinecraftServer.js" from root
Unexpected token ILLEGAL
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at c (/SpaceCP/houston.js:4:212)
    at b (/SpaceCP/houston.js:4:895)
    at /SpaceCP/houston.js:4:17010
    at /SpaceCP/houston.js:4:15536
    at Object.oncomplete (fs.js:107:15) Error: failed to require "/SpaceCP//addons/houston_game_minecraft/MinecraftServer.js" from root
Unexpected token ILLEGAL
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at c (/SpaceCP/houston.js:4:212)
    at b (/SpaceCP/houston.js:4:895)
    at /SpaceCP/houston.js:4:17010
    at /SpaceCP/houston.js:4:15536
    at Object.oncomplete (fs.js:107:15)
    at c (/SpaceCP/houston.js:4:232)
    at b (/SpaceCP/houston.js:4:895)
    at /SpaceCP/houston.js:4:17010
    at /SpaceCP/houston.js:4:15536
    at Object.oncomplete (fs.js:107:15)
info: Houston will now shut down...

**Comment by slossgaming** [comment]
Im using UBUNTU Server, and it is running nodejs

**Comment by Mar0xy** [comment]
Weird I didn't run into this error when installing it on ubuntu 16.04 lts

**Comment by JamyDev** [comment]
Old version of nodeJS, please upgrade to node version 6
