### ISSUE TITLE
File manager, schedules, and plugins not loading.

### ISSUE THREAD

**Issue by EqlipseD** [SpaceCP/Bugs#32]
Specific steps to reproduce the issue:
I recently updated to the latest release of Houston and then this started to happen. It happened when SpaceCP first came out but it seemed to have gone away when the second update of Houston was pushed. All I simply do is login to the panel and go to the file manager and it gives me an error saying "there was an error retrieving files from /". This happened awhile back on the second update of Houston but restart of the daemon fixed the issue but it is not being resolved now.

Browser:
Chrome

Operating system of your daemon:
Ubuntu
Release 10.04 (precise) 64bit
Kernel Linux 3.10.23.xxxx-std-ipv6-64
GNOME 3.4.2

What game and mod the issue occurred on:
Minecraft

What area of the panel the issue occurred on:
File manager, schedules, and plugins

Was there any code or error displayed? (F12 in chrome and click on the red X's on the near-bottom right if its there and include those errors):

Error: "id" must be a string or a number!
    at Object.d [as _snErr](https://app.spacecp.net/js/spacecp.js?build=c2223db:575:8345)
    at e.i (https://app.spacecp.net/js/spacecp.js?build=c2223db:584:10967)
    at e.t.default.get (https://app.spacecp.net/js/spacecp.js?build=c2223db:584:14348)
    at e.!.t.(anonymous function).n.(anonymous function).shorthand.s.(anonymous function) [as get](https://app.spacecp.net/js/spacecp.js?build=c2223db:584:20519)
    at new s (https://app.spacecp.net/js/spacecp.js?build=c2223db:649:14784)
    at Object.fn (https://app.spacecp.net/js/spacecp.js?build=c2223db:663:10476)
    at m.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:130:114)
    at m.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:133:113)
    at m.e.$safeApply (https://app.spacecp.net/js/spacecp.js?build=c2223db:663:15794)
    at n.<anonymous> (https://app.spacecp.net/js/spacecp.js?build=c2223db:646:22335)(anonymous function) @ angular.js:12416  

https://app.spacecp.net/assets/contexts/%7B%7Bspacecp.current.context.token%7D%7D/img/banner.jpg Failed to load resource: the server responded with a status of 404 (Not Found)

TypeError: Cannot read property 'slice' of undefined
    at Object.v.scheduleTable.o.getData (/js/e0f0e4def52bdca09630.js:1)
    at Object.<anonymous> (spacecp.js:185)
    at m (spacecp.js:185)
    at v (spacecp.js:185)
    at reload (spacecp.js:185)
    at /js/e0f0e4def52bdca09630.js:1
    at m.e.$safeApply (spacecp.js:663)
    at c (/js/e0f0e4def52bdca09630.js:1)
    at n.<anonymous> (spacecp.js:649)
    at spacecp.js:646(anonymous function) @ angular.min.js:107(anonymous function) @ angular.min.js:80m.$apply @ angular.min.js:133e.$safeApply @ spacecp.js:663(anonymous function) @ spacecp.js:646n @ spacecp.js:648n.emit @ spacecp.js:648n.onPacket @ spacecp.js:648r.onPacket @ spacecp.js:648n.onPacket @ spacecp.js:648n.onData @ spacecp.js:648websocket.onmessage @ spacecp.js:648
spacecp.js:646 <<<< POST/api/v2/servers/566882637586d10242baa788/api Object

**Comment by JamyDev** [comment]
Thanks for the report, I'll look into this.

**Comment by Antariano** [comment]
Fix incoming
