### ISSUE TITLE
Installing plugins from panel...

### ISSUE THREAD

**Issue by EqlipseD** [SpaceCP/Bugs#33]
Specific steps to reproduce the issue:
Trying to install plugins from Spigot, Mediafire, or Dropbox. Nothing will install properly unless it is from Bukkit. Also if I try and install a plugin by uploading it directly to the dedicated server and use the plugman plugin to load the plugin I get an error in the console and the plugin does not load.

Browser:
Chrome

Operating system of your daemon:
Ubuntu
Release 10.04 (precise) 64bit
Kernel Linux 3.10.23.xxxx-std-ipv6-64
GNOME 3.4.2

What game and mod the issue occurred on:
Minecraft

What area of the panel the issue occurred on:

Errors in console:
[17:09:15] [Server thread/INFO]: iQon issued server command: /plugman load Mobstack
[17:09:15] [Server thread/INFO]: [MobStack] Enabling MobStack v1.0
[17:09:15] [Server thread/ERROR]: Could not pass event PluginEnableEvent to Houston v1.0-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:285) [PlugMan.jar:?]
    at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?]
    at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104) [PlugMan.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
    at net.xereo.houston.bukkit.plugin.HoustonPluginManager.onPluginEnabled(HoustonPluginManager.java:383) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
    ... 24 more

Request:
Maybe an easier way to upload plugin from the panel would be nice. I have seen other panels use a drag and drop feature, that would suite this just fine in my opinion. That is if it is possible. If not being able to have DropBox or a Mediafire account linked some how would be great as well.

**Comment by Antariano** [comment]
This seems to be an issue with `SimplePluginManager` so nothing we can do there.
As for the first part, I'm going to port it to a separate issue so we keep things clean.

**Comment by Antariano** [comment]
To answer your feature request, it's something we have on the roadmap :)

**Comment by JamyDev** [comment]
Please report it to the SimplePluginManager team and tell them how to reproduce it btw ;)
