### ISSUE TITLE
server restart after midnight causes java log error

### ISSUE THREAD

**Issue by wizdude** [SpaceCP/Bugs#62]
i'm unsure whether this is related to the panel/houston at all, or whether i've discovered some weird minecraft bug.

i can't recreate this error now - but i believe it's because i restarted the server instance just after midnight.

see log below:

[restarted-vanilla-server-log-error.txt](https://github.com/SpaceCP/Bugs/files/68524/restarted-vanilla-server-log-error.txt)

**Comment by wizdude** [comment]
the error occurs during the stop server part.

the first part of the error looks like:

```
- iwish-and-daddy-server: 2015-12-22 00:01:06,475 ERROR Attempted to append to non-started appender File
- iwish-and-daddy-server: 2015-12-22 00:01:06,477 ERROR Unable to write to stream logs/latest.log for appender File
- iwish-and-daddy-server: 2015-12-22 00:01:06,477 ERROR An exception occurred processing Appender File org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to RandomAccessFile logs/latest.log
- iwish-and-daddy-server:       at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.flush(RollingRandomAccessFileManager.java:109)
- iwish-and-daddy-server:       at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.write(RollingRandomAccessFileManager.java:90)
- iwish-and-daddy-server:       at org.apache.logging.log4j.core.appender.OutputStreamManager.write(OutputStreamManager.java:129)
- iwish-and-daddy-server:       at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:113)
- iwish-and-daddy-server:       at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender.append(RollingRandomAccessFileAppender.java:96)
- iwish-and-daddy-server:       at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
- iwish-and-daddy-server:       at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
- iwish-and-daddy-server:       at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
- iwish-and-daddy-server:       at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
- iwish-and-daddy-server:       at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
- iwish-and-daddy-server:       at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1011)
- iwish-and-daddy-server:       at net.minecraft.server.MinecraftServer.t(SourceFile:376)
- iwish-and-daddy-server:       at net.minecraft.server.MinecraftServer$2.run(SourceFile:715)
- iwish-and-daddy-server: Caused by: java.io.IOException: Stream Closed
- iwish-and-daddy-server:       at java.io.RandomAccessFile.writeBytes(Native Method)
- iwish-and-daddy-server:       at java.io.RandomAccessFile.write(RandomAccessFile.java:525)
- iwish-and-daddy-server:       at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.flush(RollingRandomAccessFileManager.java:106)
- iwish-and-daddy-server:       ... 12 more
```

as mentioned I can restart now and not receive the error. this message never appeared on my other vanilla or spigot test servers.

**Comment by JamyDev** [comment]
It might seem that the logreader doesn't close the file correctly, which is why it might fail to roll it over after a restart. Thanks for bringing this to my attention.

**Comment by tlaundal** [comment]
I was able to recreate this once, but then not again.

My error, which is the same as the one in the log file you attached (but you cut off some in the paste above) is this:

```
- vanilla: [14:58:31] [Server Shutdown Thread/INFO]: Stopping server
- vanilla: 2016-01-02 14:58:31,087 ERROR Unable to write to stream logs/latest.log for appender File
- vanilla: 2016-01-02 14:58:31,088 ERROR An exception occurred processing Appender File org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to RandomAccessFile logs/latest.log
- vanilla:      at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.flush(RollingRandomAccessFileManager.java:109)
- vanilla:      at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.write(RollingRandomAccessFileManager.java:90)
- vanilla:      at org.apache.logging.log4j.core.appender.OutputStreamManager.write(OutputStreamManager.java:129)
- vanilla:      at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:113)
- vanilla:      at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender.append(RollingRandomAccessFileAppender.java:96)
- vanilla:      at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
- vanilla:      at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
- vanilla:      at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
- vanilla:      at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
- vanilla:      at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
- vanilla:      at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1011)
- vanilla:      at net.minecraft.server.MinecraftServer.t(SourceFile:376)
- vanilla:      at net.minecraft.server.MinecraftServer$2.run(SourceFile:715)
- vanilla: Caused by: java.io.IOException: Stream Closed
- vanilla:      at java.io.RandomAccessFile.writeBytes(Native Method)
- vanilla:      at java.io.RandomAccessFile.write(Unknown Source)
- vanilla:      at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.flush(RollingRandomAccessFileManager.java:106)
- vanilla:      ... 12 more
- vanilla: Exception in thread "Server Shutdown Thread" org.apache.logging.log4j.core.appender.AppenderLoggingException: Attempted to append to non-started appender ServerGuiConsole
- vanilla:      at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
- vanilla:      at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
- vanilla:      at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
- vanilla:      at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
- vanilla:      at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
- vanilla:      at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1011)
- vanilla:      at net.minecraft.server.MinecraftServer.t(SourceFile:376)
- vanilla:      at net.minecraft.server.MinecraftServer$2.run(SourceFile:715)
- vanilla: 2016-01-02 14:58:31,090 ERROR Attempted to append to non-started appender ServerGuiConsole
info: vanilla: Server stopped
- vanilla: [14:58:34] [Server thread/INFO]: Starting minecraft server version 1.8.9
```

The next to last line is important: `ERROR Attempted to append to non-started appender ServerGuiConsole`.
I think this happens because Houston tries to start the server without the `nogui` command line argument. Minecraft sees that it cannot open the GUI, so it doesn't open it, but for some reason, sometimes when the server stops, it will try to close the log appender for the GUI console, which causes this error.

@JamyDev We can't verify this is the case, but vanilla servers should always have the `nogui` argument, at least.

**Comment by JamyDev** [comment]
@totokaka `mogui` is always added, see this code:

```
$server.runtime.args =
            exec["java-runtime-args"].concat(
                // Memory
                "-Xmx" + javaMem,
                //
                // Terminal support
                "-Djline.terminal=jline.UnsupportedTerminal",
                // Load a jar file
                "-jar",
                exec.jarfile,
                exec.args,
                "nogui");
```

In regards to the logs, I should have this fixed in the next build
