### ISSUE TITLE
Houston Plugin error on server start

### ISSUE THREAD

**Issue by tobiasnagel** [SpaceCP/Bugs#78]
After starting a Spigot Server on a fresh install of Houston, i get the following error:

```
ardacraft: java.lang.NoSuchMethodError: java.nio.file.Files.newBufferedReader(Ljava/nio/file/Path;)Ljava/io/BufferedReader;
 ardacraft:    at net.xereo.houston.java.plugin.ManagedPlugin.load(ManagedPlugin.java:212) ~[?:?]
 ardacraft:    at net.xereo.houston.java.plugin.HoustonPluginManager.loadPlugins(HoustonPluginManager.java:185) ~[?:?]
 ardacraft:    at net.xereo.houston.bukkit.HoustonBukkit.onEnable(HoustonBukkit.java:88) ~[?:?]
 ardacraft:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8-2.jar:git-Spigot-db6de12-18fbb24]
 ardacraft:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8-2.jar:git-Spigot-db6de12-18fbb24]
 ardacraft:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8-2.jar:git-Spigot-db6de12-18fbb24]
 ardacraft:    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8-2.jar:git-Spigot-db6de12-18fbb24]
 ardacraft:    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8-2.jar:git-Spigot-db6de12-18fbb24]
 ardacraft:    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8-2.jar:git-Spigot-db6de12-18fbb24]
 ardacraft:    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8-2.jar:git-Spigot-db6de12-18fbb24]
 ardacraft:    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8-2.jar:git-Spigot-db6de12-18fbb24]
 ardacraft:    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8-2.jar:git-Spigot-db6de12-18fbb24]
 ardacraft:    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8-2.jar:git-Spigot-db6de12-18fbb24]
 ardacraft:    at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
 ardacraft: [12:57:07 INFO]: Done (62,303s)! For help, type "help" or "?"
<Buffer 46 45 48 4c 45 52 3a 0d 0d 0a 42 65 73 63 68 72 65 69 62 75 6e 67 20 3d 20 41 75 73 6e 61 68 6d 65 66 65 68 6c 65 72 20 61 75 66 67 65 74 72 65 74 65 ... >
29 Dec 12:57:37 - uncaughtException: 9df4cf3d2a4844c99431e763f6640468
Cannot read property 'replace' of undefined TypeError: Cannot read property 'replace' of undefined
    at ChildProcess.<anonymous> (C:\SpaceCP\SpaceCPDeamon\node_modules\pidusage\lib\stats.js:136:26)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
info: Houston will now shut down...
 ardacraft: [12:57:39 INFO]: [Server] * *STOPPING SERVER!**
 ardacraft: [12:57:40 INFO]: Saving...
 ardacraft: [12:57:40 INFO]: Saved the world
 ardacraft: [12:57:42 INFO]: Stopping the server
 ardacraft: [12:57:42 INFO]: Stopping server
 ardacraft: [12:57:42 INFO]: [Houston] Disabling Houston v1.0-SNAPSHOT
 ardacraft: [12:57:42 INFO]: Saving players
 ardacraft: [12:57:42 INFO]: Saving worlds
 ardacraft: [12:57:42 INFO]: Saving chunks for level 'world'/Overworld
 ardacraft: [12:57:42 INFO]: Saving chunks for level 'world_nether'/Nether
 ardacraft: [12:57:42 INFO]: Saving chunks for level 'world_the_end'/The End
info: ardacraft: Server stopped
info: Houston exiting.
```

Details:
Spigot 1.8.8
OS: Windows Server 2012 R2
Houston Build: 172
mfg. Tobi

**Comment by tlaundal** [comment]
This is a small mistake I made in HoustonBukkit. If you update to java 8 the problem will go away.

For the next build we will restore compatibility with java 7.
